name: Build And Deploy to CH2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    env:
      CONNECTEDAPP_CLIENT_ID: ${{ secrets.CONNECTEDAPP_CLIENT_ID }}
      CONNECTEDAPP_CLIENT_SECRET: ${{ secrets.CONNECTEDAPP_CLIENT_SECRET }} 
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      ENV_CLIENT_ID: ${{ secrets.ENV_CLIENT_ID }} 
      ENV_CLIENT_SECRET: ${{ secrets.ENV_CLIENT_SECRET }}

    steps:
    - name: Step1:Checkout Code Repo
      uses: actions/checkout@v4
      
    - name: Step2:Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step3:Publish
      run: mvn deploy -Dmule.env=Dev -s settings.xml
      
    - name: Step4:Deploy
      run: mvn deploy -DmuleDeploy -Dmule.env=Dev -s settings.xml
